# Generated by Django 5.0.6 on 2024-06-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='list_description',
            field=models.TextField(default='Default list description'),
        ),
    ]
