# Generated by Django 5.0.6 on 2024-06-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_list_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepage',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='coursepage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='desc'),
        ),
    ]
